name: Build All
on: [workflow_dispatch]
jobs:
  build:
    runs-on: self-hosted
    timeout-minutes: 1440
    steps:
      - uses: actions/checkout@v2

      - name: run feather script
        run: python3 build_all.py
