name: Build All
on: [workflow_dispatch]
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - name: run feather script
        run: python3 feather.py clean build javadocJar checkMappings mapNamedJar
