name: Build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: openjdk:17-jdk
      options: --user root
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1

      - name: set up python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: install python packages
        run: python -m pip install --upgrade pip

      - name: run feather script
        run: python feather.py build javadocJar checkMappings mapNamedJar
