name: Publish
on: [workflow_dispatch]
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: run feather script
        run: python3 feather.py clean publish
        env:
          MAVEN_URL: ${{ secrets.NEW_MAVEN_URL }}
          MAVEN_USERNAME: ${{ secrets.NEW_MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.NEW_MAVEN_PASSWORD }}
