name: Publish
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: openjdk:17-jdk
      options: --user root
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1

      - name: Generate build number
        id: buildnumber
        uses: einaregilsson/build-number@v3
        with:
          token: ${{ secrets.github_token }}
          prefix: ${{ github.ref }}

      - run: ./gradlew publish --stacktrace
        env:
          MAVEN_PUBLISH_TOKEN: ${{ secrets.MAVEN_PUBLISH_TOKEN }}
